export const Roles = [
    { label: "Frontend", value: "frontend" , heading:"ENGINEERING"},
    { label: "Backend", value: "backend",  heading:"ENGINEERING"},
    { label: "Fullstack", value: "fullstack"  , heading:"ENGINEERING"},
    { label: "Flutter", value: "flutter"  , heading:"ENGINEERING"},
    { label: "Android", value: "android" , heading:"ENGINEERING" },
    { label: "React Native", value: "react native" , heading:"ENGINEERING" },
    { label: "Tech Lead", value: "tech lead"  , heading:"ENGINEERING"},
    { label: "Dev-Ops", value: "dev-ops"  , heading:"ENGINEERING"},
    { label: "Data Engineer", value: "data engineer"  , heading:"ENGINEERING"},
    { label: "Data Science", value: "data science"  , heading:"ENGINEERING"},
    { label: "Computer-Vision", value: "computer-vision" , heading:"ENGINEERING" },
    { label: "NLP", value: "nlp"  , heading:"ENGINEERING"},
    { label: "Deep-Learning", value: "deep-learning" ,heading:"ENGINEERING" },
    { label: "Test / Qa", value: "test / qa", heading:"ENGINEERING"},
    { label: "Web3", value: "web3" , heading:"ENGINEERING"},
    { label: "SRE", value: "sre", heading:"ENGINEERING" },
    { label: "Data-Infrastructure", value: "data-infrastructure" , heading:"ENGINEERING"},
    { label: "Designer", value: "designer", heading:"DESIGN" },
    { label: "Design Manager", value: "design manager", heading:"DESIGN" },
    { label: "Graphic Designer", value: "graphic designer", heading:"DESIGN" },
    { label: "Product Designer", value: "product designer", heading:"DESIGN" },
    { label: "Product Manager", value: "product manager", heading:"PRODUCT" },
    { label: "Operations Manager", value: "operations manager", heading:"OPERATIONS" },
    { label: "Founder's Office / Chief of Staff", value: "founder's office / chief of staff", heading:"OPERATIONS" },
    { label: "Sales Development Representative", value: "Sales Development Representative", heading:"SALES" },
    { label: "Account Executive", value: "Account Executive", heading:"SALES" },
    { label: "Account Manager", value: "Account manager", heading:"SALES" },
    { label: "Digital Marketing Manager", value: "Digital Marketing Manager", heading:"MARKETING" },
    { label: "Growth Hacker", value: "Growth Hacker", heading:"MARKETING" },
    { label: "Marketing", value: "Marketing", heading:"MARKETING" },
    { label: "Product Marketing Manager", value: "Product Marketing Manager", heading:"MARKETING" },
    { label: "Hardware", value: "Hardware", heading:"OTHER ENGINEERING" },
    { label: "Mechanical", value: "Mechanical", heading:"OTHER ENGINEERING" },
    { label: "Systems", value: "Systems", heading:"OTHER ENGINEERING" },
    { label: "Business Analystt", value: "Business Analystt", heading:"BUSINESS ANALYSTT" },
    { label: "Data Analystt", value: "Data Analystt", heading:"DATA ANALYSTT" },
    { label: "Product Manager", value: "Product Manager", heading:"PRODUCT MANAGER" },
    { label: "Management", value: "Management", heading:"MANAGEMENT" },
    { label: "Legal", value: "Legal", heading:"LEGAL" },
    { label: "HR", value: "HR", heading:"HR" },
    { label: "Finance", value: "Finance", heading:"FINANCE" },
  ];

  export const numberOfEmployees = [
    {label:"1-10", value:"1-10"},
    {label:"11-20", value:"11-20"},
    {label:"21-50", value:"21-50"},
    {label:"51-100", value:"51-100"},
    {label:"101-200", value:"101-200"},
    {label:"201-500", value:"201-500"},
    {label:"500+", value:"500+"}
  ]

  export const Experience = [
    {label:"1", value:"1"},
    {label:"2", value:"2"},
    {label:"3", value:"3"},
    {label:"4", value:"4"},
    {label:"5", value:"5"},
    {label:"6", value:"6"},
    {label:"7", value:"7"},
    {label:"8", value:"8"},
    {label:"9", value:"9"},
    {label:"10", value:"10"},
  ]

  export const Remote=[
    {label:"Remote", value:"Remote"},
    {label:"Office", value:"Office"},
    {label:"Hybrid", value:"Hybrid"},
  ]

  export const MiniBasePay=[
    {label:"0L", value:"0"},
    {label:"10L", value:"10"},
    {label:"20L", value:"20"},
    {label:"30L", value:"30"},
    {label:"40L", value:"40"},
    {label:"50L", value:"50"},
    {label:"60L", value:"60"},
    {label:"70L", value:"70"},
  ]